name: Build & Test

on:
  #  push:
  #    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile # yarn 사용시 npm ci 와 같다 # run: npm ci

      - name: Build & Test
        run: |
          npm run ci:build
          npm run ci:test

      # docs
      - name: Build document
        run: |
          npm run page:clear
          npm run page:expose

      - name: Github pages publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-runners-access-token-github_token
          publish_dir: './docs'